name: Build and Deploy to Google Cloud Platform

on:
  push:
    branches:
      - master
      - refactoring
    files:
      - .github/workflows/deploy-gcp.yml

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_INSTANCE: tuya-credit-fe
  GCP_INSTANCE_ZONE: us-west1-b

jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect to GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Use gcloud CLI
      run: |
        gcloud workflows deploy myWorkflowFromGitHub \
        --location ${{ env.GCP_INSTANCE_ZONE }} \
        --source deploy-gcp.workflows.yaml \
        --project ${{ secrets.GCP_PROJECT }} \
        --labels "commit-sha=${{ github.sha }}" \
        --service-account ${{ env.GCP_INSTANCE }}@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
