name: Publish on Expo Go (Staging)

on:
  push:
    branches:
      - dev
      - release/*
    files:
      - .github/workflows/expo-publish-staging.yml

jobs:
  login-publish:
    name: Expo App Login and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn

    - name: Install Expo CLI
      run: yarn global add expo-cli@5.4.3

    - name: Expo Login
      run: |
        yarn expo:login -- -u ${{ secrets.EXPO_STAGING_USER }} -p ${{ secrets.EXPO_STAGING_PASS }}

    - name: Expo Publish
      run: |
        yarn expo:publish
