name: Build and Deploy to Google Cloud Platform

on:
  push:
    branches:
      - master
      - refactoring
    files:
      - .github/workflows/expo-publish.yml

jobs:
  login-publish:
    name: Expo App Login and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Expo Login
      run: |
        npm run login -- -u ${{ secrets.EXPO_USER }} -p ${{ secrets.EXPO_PASS }}

    - name: Expo Publish
      run: |
        npm run publish
